# Generated by Django 5.1.7 on 2025-03-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['city_id'], name='events_city_city_id_d9f25c_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['state'], name='events_city_state_i_265b47_idx'),
        ),
    ]
