# Generated by Django 5.1.7 on 2025-03-07 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_seed_organizers_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.state'),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.city'),
        ),
    ]
