# Generated by Django 5.1.7 on 2025-03-07 18:10

from django.db import migrations, models
from django.utils.text import slugify

def populate_event_slugs(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    
    for event in Event.objects.all():
        original_slug = slugify(event.title)
        slug = original_slug
        counter = 1
        
        while Event.objects.filter(slug=slug).exists():
            slug = f"{original_slug}-{counter}"
            counter += 1
            
        event.slug = slug
        event.save()

def populate_organizer_slugs(apps, schema_editor):
    Organizer = apps.get_model('events', 'Organizer')
    
    for organizer in Organizer.objects.all():
        original_slug = slugify(organizer.company_name)
        slug = original_slug
        counter = 1
        
        while Organizer.objects.filter(slug=slug).exists():
            slug = f"{original_slug}-{counter}"
            counter += 1
            
        organizer.slug = slug
        organizer.save()

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_populate_category_slugs'),
    ]

    operations = [
        # Add Event slug field with null allowed initially
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        # Populate Event slugs
        migrations.RunPython(populate_event_slugs),
        # Make Event slug unique and non-null
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        # Add Organizer slug field with null allowed initially
        migrations.AddField(
            model_name='organizer',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        # Populate Organizer slugs
        migrations.RunPython(populate_organizer_slugs),
        # Make Organizer slug unique and non-null
        migrations.AlterField(
            model_name='organizer',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        # Add the image fields
        migrations.AddField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, help_text='Landscape image for event banner', null=True, upload_to='events/banners/'),
        ),
        migrations.AddField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Square image for event thumbnail', null=True, upload_to='events/thumbnails/'),
        ),
    ]