# Generated by Django 5.1.7 on 2025-03-18 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_attendee_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, default='Entrada para o evento', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='name',
            field=models.CharField(default='Ingresso Regular', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.event', verbose_name='Event'),
        ),
    ]
