# Generated by Django 5.1.7 on 2025-03-22 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_ticket_description_ticket_name_alter_ticket_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
