# Generated by Django 5.1.7 on 2025-03-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_advertisementsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check-in time'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='checked_in',
            field=models.BooleanField(default=False, verbose_name='Checked in'),
        ),
    ]
