# Generated by Django 5.1.7 on 2025-03-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='BRL', max_length=3),
        ),
    ]
