# Generated by Django 5.1.7 on 2025-03-22 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_delete_payment'),
        ('payments', '0002_alter_payment_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='events.order'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
